language: node_js
node_js:
  - "10"
  - "12"
services:
  - docker
cache: yarn
script:
  - sed -i "1!b;s/node:12/node:$TRAVIS_NODE_VERSION/" .devcontainer/Dockerfile
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec vega yarn test
