language: node_js
node_js:
  - "10"
  - "12"
dist: bionic
services:
  - docker
cache: yarn
script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec vega yarn
  - docker-compose exec vega yarn test
